/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Sora', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      colors: {
        orange: '#FF6B35',
        teal: '#00D4AA',
        'dark-navy': '#0A1128',
        'gray-50': '#FAFAFA',
        'gray-100': '#F5F5F5',
        'gray-200': '#E5E5E5',
        'gray-300': '#D4D4D4',
        'gray-700': '#404040',
        'gray-900': '#171717',
        'on-tertiary-fixed-variant': '#332dbc',
        'surface-container-highest': '#353534',
        'tertiary-fixed-dim': '#c2c1ff',
        'on-surface': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-primary-fixed': '#001a41',
        'surface': '#131313',
        'on-secondary-fixed': '#2d1600',
        'on-secondary-container': '#633700',
        'secondary-fixed': '#ffdcbf',
        'on-error': '#690005',
        'secondary-container': '#fe9400',
        'on-tertiary': '#1800a7',
        'outline-variant': '#414755',
        'on-background': '#e5e2e1',
        'primary-container': '#4b8eff',
        'outline': '#8b90a0',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d8e2ff',
        'on-surface-variant': '#c1c6d7',
        'surface-tint': '#adc6ff',
        'on-primary-container': '#00285c',
        'secondary-fixed-dim': '#ffb874',
        'surface-dim': '#131313',
        'on-primary-fixed-variant': '#004493',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'on-primary': '#002e69',
        'inverse-primary': '#005bc1',
        'tertiary-fixed': '#e2dfff',
        'tertiary': '#c2c1ff',
        'on-secondary': '#4b2800',
        'surface-container-high': '#2a2a2a',
        'on-secondary-fixed-variant': '#6a3b00',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#adc6ff',
        'on-tertiary-container': '#140094',
        'primary': '#adc6ff',
        'background': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'inverse-on-surface': '#313030',
        'on-tertiary-fixed': '#0c006b',
        'error-container': '#93000a',
        'tertiary-container': '#8382ff',
        'secondary': '#ffbc7c',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        'hero-gradient': 'linear-gradient(180deg, rgba(0,0,0,0.55), rgba(0,0,0,0.75))',
        'cta-gradient': 'linear-gradient(135deg, #FF6B35 0%, #FF8F70 100%)',
      },
      boxShadow: {
        glow: '0 20px 50px rgba(102, 126, 234, 0.25)',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.7 },
        },
      },
      animation: {
        float: 'float 3s ease-in-out infinite',
        pulseGlow: 'pulseGlow 2.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

